services:
  # Base de datos PostgreSQL local
  postgres:
    image: postgres:16-alpine
    container_name: nice_order_db
    restart: always
    environment:
      POSTGRES_USER: nice_user
      POSTGRES_PASSWORD: nice_secure_password
      POSTGRES_DB: nice_order_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nice_user -d nice_order_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local